### PR TITLE
Add Ada formatting support with gnatpp

### PR DESCRIPTION
**Pull request by TamaMcGlinn**
It's the standard formatter for Ada code.

### CODE REVIEW

**Comment by Chiel92** [comment]
It looks like this will format the file on disk instead of the buffer in Vim, correct? I think you need to somehow specify that it needs to read from stdin.

**Comment by TamaMcGlinn** [comment]
You are right; it doesn't seem to work yet.

**Comment by Chiel92** [comment]
The docs seem to suggest it doesn't read from stdin but reads the given filename. If you have unwritten changes and then attempt to format the vim buffer you will lose those changes, which is not correct behavior. I suspect that passing /dev/stdin instead of the filename would fix this issue, but of course that would only work for linux.

**Comment by TamaMcGlinn** [comment]
What I've been using is this:

```
  autocmd BufWritePost *.ad[sb] Autoformat | noautocmd write
```

So after writing the file, the file is re-formatted and written again but without triggering the BufWritePost a second time.

It works. Passing /dev/stdin to gnatpp does not work, as gnatpp explicitly checks that it is operating on a 'regular file'. A possible alternative would be to pass the stdin on to a temporary file and then have gnatpp read from that file.

I do see your point; mapping e.g. F3 to reformat won't work for such a formatter - it would discard your unsaved changes to the file.

**Comment by TamaMcGlinn** [comment]
It is fixed now. Please merge.

**Pull request merged**
